from django.db import models

# Create your models here.
class student(models.Model):
    name=models.CharField(max_length=264)
    email=models.CharField(max_length=264)
    batch=models.CharField(max_length=264)
class student1(models.Model):
    name = models.CharField(max_length=264)
    email = models.CharField(max_length=264)
    batch= models.CharField(max_length=264)
    vision= models.CharField(max_length=264)
    mission= models.CharField(max_length=264)
    peo= models.CharField(max_length=264)
    pos= models.CharField(max_length=264)
class staff(models.Model):
    staff_name=models.CharField(max_length=264)
class staff1(models.Model):
    staff_name=models.TextField()
    staff_email=models.TextField()
class staff2(models.Model):
    staff_name=models.TextField()
    staff_email=models.TextField()
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class parent(models.Model):
    sd=models.TextField()
    batch=models.TextField()
    occupation=models.TextField()
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class parent1(models.Model):
    parent_name=models.TextField()
    sd=models.TextField()
    batch=models.TextField()
    occupation=models.TextField()
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class Industry(models.Model):
    name = models.CharField(max_length=264)
    working_in = models.CharField(max_length=264)
    designation = models.CharField(max_length=264)
    email = models.EmailField()
    uploaded_file = models.FileField(upload_to='industry_people_id/')  # Upload directory within MEDIA_ROOT
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class Academician(models.Model):
    name = models.CharField(max_length=264)
    working_college = models.CharField(max_length=264)
    designation = models.CharField(max_length=264)
    official_mail = models.EmailField()
    uploaded_file = models.FileField(upload_to='academician_files/')
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class Alumni(models.Model):
    name = models.CharField(max_length=264)
    batch_studied = models.CharField(max_length=264)
    currently_working = models.CharField(max_length=264)
    designation = models.CharField(max_length=264)
    official_mail = models.EmailField()
    uploaded_file = models.FileField(upload_to='alumni_files/')
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class Alumni1(models.Model):
    name = models.CharField(max_length=264)
    batch_studied = models.CharField(max_length=264)
    currently_working = models.CharField(max_length=264)
    designation = models.CharField(max_length=264)
    official_mail = models.EmailField()
    uploaded_file = models.BinaryField()
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class Academician1(models.Model):
    name = models.CharField(max_length=264)
    working_college = models.CharField(max_length=264)
    designation = models.CharField(max_length=264)
    official_mail = models.EmailField()
    uploaded_file = models.BinaryField()
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()
class Industry1(models.Model):
    name = models.CharField(max_length=264)
    working_in = models.CharField(max_length=264)
    designation = models.CharField(max_length=264)
    email = models.EmailField()
    uploaded_file = models.BinaryField()# Upload directory within MEDIA_ROOT
    vision= models.TextField()
    mission= models.TextField()
    peo= models.TextField()
    pos= models.TextField()