# Generated by Django 4.1.5 on 2023-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_parent1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('working_in', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('uploaded_file', models.FileField(upload_to='industry_files/')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('peo', models.TextField()),
                ('pos', models.TextField()),
            ],
        ),
    ]
