# Generated by Django 4.1.5 on 2023-08-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('working_college', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('official_mail', models.EmailField(max_length=254)),
                ('uploaded_file', models.FileField(upload_to='academician_files/')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('peo', models.TextField()),
                ('pos', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='industry',
            name='uploaded_file',
            field=models.FileField(upload_to='industry_people_id/'),
        ),
    ]
