# Generated by Django 4.1.5 on 2023-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_academician_alter_industry_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('batch_studied', models.CharField(max_length=264)),
                ('currently_working', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('official_mail', models.EmailField(max_length=254)),
                ('uploaded_file', models.FileField(upload_to='alumni_files/')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('peo', models.TextField()),
                ('pos', models.TextField()),
            ],
        ),
    ]
