# Generated by Django 4.1.5 on 2023-08-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academician1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('working_college', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('official_mail', models.EmailField(max_length=254)),
                ('uploaded_file', models.BinaryField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('peo', models.TextField()),
                ('pos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumni1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('batch_studied', models.CharField(max_length=264)),
                ('currently_working', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('official_mail', models.EmailField(max_length=254)),
                ('uploaded_file', models.BinaryField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('peo', models.TextField()),
                ('pos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('working_in', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('uploaded_file', models.BinaryField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('peo', models.TextField()),
                ('pos', models.TextField()),
            ],
        ),
    ]
